{% set version = "3.98-1.13" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xml
  version: {{ version|replace("-", "_") }}

source:
  fn: XML_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/XML_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/XML/XML_{{ version }}.tar.gz


  sha256: e43179327dd1d8404a491979892bb13c227494afa0601ae34e1ad85f7301a277

build:
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/
  skip: True  # [win32]

requirements:
  build:
    - r-base
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]
    - libxml2 2.9.*

  run:
    - r-base
    - libxml2 2.9.*

test:
  commands:
    - $R -e "library('XML')"  # [not win]
    - "\"%R%\" -e \"library('XML')\""  # [win]



about:
  home: http://www.omegahat.net/RSXML
  license: BSD_2_clause
  summary: Many approaches for both reading and creating XML (and HTML) documents (including
    DTDs), both local and accessible via HTTP or FTP.  Also offers access to an 'XPath'
    "interpreter".
  license_family: BSD
  license_file: LICENSE



extra:
  recipe-maintainers:
    - croth1
