{% set version = "3.99-0.17" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-xml
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/XML_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/XML/XML_{{ version }}.tar.gz
  sha256: 6e233265ff69ff2f59f56fe4abc5af70e2cfa6d99aec6ad2afd2bf2c0d98a2d8

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - libxml2
  run:
    - r-base
    - libxml2

test:
  commands:
    - $R -e "library('XML')"           # [not win]
    - "\"%R%\" -e \"library('XML')\""  # [win]

about:
  home: http://www.omegahat.net/RSXML
  license: BSD-2-Clause
  summary: Many approaches for both reading and creating XML (and HTML) documents (including DTDs), both local and accessible via HTTP or FTP.  Also offers access to an 'XPath' "interpreter".
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_2_clause
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - croth1
